// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzJirQ3HanHkNJ_Il00rYezyjqgSPywkk',
    appId: '1:1016984430150:web:41d9b57843ee09ea654c47',
    messagingSenderId: '1016984430150',
    projectId: 'otpvarification-e3388',
    authDomain: 'otpvarification-e3388.firebaseapp.com',
    storageBucket: 'otpvarification-e3388.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl2YSQkbdf8o4IhSb6CMXWC5I3yQlSCm0',
    appId: '1:1016984430150:android:9893b0bed12ebd0f654c47',
    messagingSenderId: '1016984430150',
    projectId: 'otpvarification-e3388',
    storageBucket: 'otpvarification-e3388.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_0sUVAwLHiNZYQQGHam6Mbw9205loVbg',
    appId: '1:1016984430150:ios:bf01b6bb9e9943de654c47',
    messagingSenderId: '1016984430150',
    projectId: 'otpvarification-e3388',
    storageBucket: 'otpvarification-e3388.appspot.com',
    iosBundleId: 'com.example.otpVarification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_0sUVAwLHiNZYQQGHam6Mbw9205loVbg',
    appId: '1:1016984430150:ios:bf01b6bb9e9943de654c47',
    messagingSenderId: '1016984430150',
    projectId: 'otpvarification-e3388',
    storageBucket: 'otpvarification-e3388.appspot.com',
    iosBundleId: 'com.example.otpVarification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzJirQ3HanHkNJ_Il00rYezyjqgSPywkk',
    appId: '1:1016984430150:web:8c4f32a1410f47f9654c47',
    messagingSenderId: '1016984430150',
    projectId: 'otpvarification-e3388',
    authDomain: 'otpvarification-e3388.firebaseapp.com',
    storageBucket: 'otpvarification-e3388.appspot.com',
  );
}
